local function ArcadeEventsTesterRegister(object)

	--green
	object:GetWidget('ArcadeTesterButton0'):SetCallback('onclick', function(widget)
		queueEvent('multikill'		, {nbrKilled = 2, name = 'Kairus', icon = '/ui/shared/textures/hero_icons/carter_full.tga', isGood = true})
	end)
	object:GetWidget('ArcadeTesterButton1'):SetCallback('onclick', function(widget)
		queueEvent('multikill'		, {nbrKilled = 3, name = 'Kairus', icon = '/ui/shared/textures/hero_icons/carter_full.tga', isGood = true})
	end)
	object:GetWidget('ArcadeTesterButton2'):SetCallback('onclick', function(widget)
		queueEvent('multikill'		, {nbrKilled = 4, name = 'Kairus', icon = '/ui/shared/textures/hero_icons/carter_full.tga', isGood = true})
	end)
	object:GetWidget('ArcadeTesterButton3'):SetCallback('onclick', function(widget)
		queueEvent('multikill'		, {nbrKilled = 5, name = 'Kairus', icon = '/ui/shared/textures/hero_icons/carter_full.tga', isGood = true})
	end)
	object:GetWidget('ArcadeTesterButton4'):SetCallback('onclick', function(widget)
		queueEvent('killstreak'		, {name = 'Kairus', isGood = true, icons = {'/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga'}})
	end)
	object:GetWidget('ArcadeTesterButton5'):SetCallback('onclick', function(widget)
		queueEvent('killstreak'		, {name = 'Kairus', isGood = true, icons = {'/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga'}})
	end)
	object:GetWidget('ArcadeTesterButton6'):SetCallback('onclick', function(widget)
		queueEvent('killstreak'		, {name = 'Kairus', isGood = true, icons = {'/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga'}})
	end)
	object:GetWidget('ArcadeTesterButton7'):SetCallback('onclick', function(widget)
		queueEvent('killstreak'		, {name = 'Kairus', isGood = true, icons = {'/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga'}})
	end)
	object:GetWidget('ArcadeTesterButton8'):SetCallback('onclick', function(widget)
		queueEvent('krytospush'		, {lane = 'bot', isGood = true, entityName='Krytos'})
	end)
	object:GetWidget('ArcadeTesterButton9'):SetCallback('onclick', function(widget)
		queueEvent('cindaradefeat'	, {isGood = true, goldReward = 350})
	end)
	object:GetWidget('ArcadeTesterButton10'):SetCallback('onclick', function(widget)
		queueEvent('baldirdefeat'	, {isGood = true, goldReward = 450})
	end)
	object:GetWidget('ArcadeTesterButton11'):SetCallback('onclick', function(widget)
		queueEvent('towerdestroyed'	, {isGood = true, entityName = 'tower', goldReward = 250})
	end)
	object:GetWidget('ArcadeTesterButton12'):SetCallback('onclick', function(widget)
		queueEvent('generatordestroyed', {isGood = true, entityName = 'generator', goldReward = 1500})
	end)
	
	--red
	object:GetWidget('ArcadeTesterButton13'):SetCallback('onclick', function(widget)
		queueEvent('multikill'		, {nbrKilled = 2, name = 'Kairus', icon = '/ui/shared/textures/hero_icons/carter_full.tga', isGood = false})
	end)
	object:GetWidget('ArcadeTesterButton14'):SetCallback('onclick', function(widget)
		queueEvent('multikill'		, {nbrKilled = 3, name = 'Kairus', icon = '/ui/shared/textures/hero_icons/carter_full.tga', isGood = false})
	end)
	object:GetWidget('ArcadeTesterButton15'):SetCallback('onclick', function(widget)
		queueEvent('multikill'		, {nbrKilled = 4, name = 'Kairus', icon = '/ui/shared/textures/hero_icons/carter_full.tga', isGood = false})
	end)
	object:GetWidget('ArcadeTesterButton16'):SetCallback('onclick', function(widget)
		queueEvent('multikill'		, {nbrKilled = 5, name = 'Kairus', icon = '/ui/shared/textures/hero_icons/carter_full.tga', isGood = false})
	end)
	object:GetWidget('ArcadeTesterButton17'):SetCallback('onclick', function(widget)
		queueEvent('killstreak'		, {name = 'Kairus', isGood = false, icons = {'/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga'}})
	end)
	object:GetWidget('ArcadeTesterButton18'):SetCallback('onclick', function(widget)
		queueEvent('killstreak'		, {name = 'Kairus', isGood = false, icons = {'/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga'}})
	end)
	object:GetWidget('ArcadeTesterButton19'):SetCallback('onclick', function(widget)
		queueEvent('killstreak'		, {name = 'Kairus', isGood = false, icons = {'/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga'}})
	end)
	object:GetWidget('ArcadeTesterButton20'):SetCallback('onclick', function(widget)
		queueEvent('killstreak'		, {name = 'Kairus', isGood = false, icons = {'/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga','/ui/shared/textures/hero_icons/carter_full.tga'}})
	end)
	object:GetWidget('ArcadeTesterButton21'):SetCallback('onclick', function(widget)
		queueEvent('krytospush'		, {lane = 'bot', isGood = false, entityName='Krytos'})
	end)
	object:GetWidget('ArcadeTesterButton22'):SetCallback('onclick', function(widget)
		queueEvent('cindaradefeat'	, {isGood = false, goldReward = 350})
	end)
	object:GetWidget('ArcadeTesterButton23'):SetCallback('onclick', function(widget)
		queueEvent('baldirdefeat'	, {isGood = false, goldReward = 450})
	end)
	object:GetWidget('ArcadeTesterButton24'):SetCallback('onclick', function(widget)
		queueEvent('towerdestroyed'	, {isGood = false, entityName = 'tower', goldReward = 250})
	end)
	object:GetWidget('ArcadeTesterButton25'):SetCallback('onclick', function(widget)
		queueEvent('generatordestroyed', {isGood = false, entityName = 'generator', goldReward = 1500})
	end)
	
	--unchanging
	object:GetWidget('ArcadeTesterButton26'):SetCallback('onclick', function(widget)
		queueEvent('respawn')
	end)
	object:GetWidget('ArcadeTesterButton27'):SetCallback('onclick', function(widget)
		queueEvent('victory')
	end)
	object:GetWidget('ArcadeTesterButton28'):SetCallback('onclick', function(widget)
		queueEvent('defeat')
	end)
	
end

ArcadeEventsTesterRegister(object)