Login = Login or {}
Login.regionsTable = {
	  -- { 'string_key', 'country_code', 'region_code', 's2_prod'},
      {'create_acc_country_other',					'OTHER',	1,	's2_prod'},      
	  {'create_acc_country_abkhazia',				'AB',		4,	'ru_prod'},
      {'create_acc_country_afghanistan',			'AF',		1,	's2_prod'},
      {'create_acc_country_algeria',				'DZ',		1,	's2_prod'},
      {'create_acc_country_aland',					'AX',		1,	's2_prod'},
      {'create_acc_country_american_samoa',			'AS',		1,	's2_prod'},
      {'create_acc_country_andorra',				'AD',		1,	's2_prod'},
      {'create_acc_country_angola',					'AO',		1,	's2_prod'},
      {'create_acc_country_anguilla',				'AI',		1,	's2_prod'},
      {'create_acc_country_antarctica',				'AQ',		1,	's2_prod'},
      {'create_acc_country_antigua_barbuda',		'AG',		1,	's2_prod'},
      {'create_acc_country_armenia',				'AM',		4,	'ru_prod'},
      {'create_acc_country_argentina',				'AR',		1,	's2_prod'},
      {'create_acc_country_aruba',					'AW',		1,	's2_prod'},
      {'create_acc_country_australia',				'AU',		1,	's2_prod'},
      {'create_acc_country_austria',				'AT',		1,	's2_prod'},
      {'create_acc_country_azerbaijan',				'AZ',		4,	'ru_prod'},
      {'create_acc_country_bahamas',				'BS',		1,	's2_prod'},
      {'create_acc_country_bahrain',				'BH',		1,	's2_prod'},
      {'create_acc_country_bangladesh',				'BD',		1,	's2_prod'},
      {'create_acc_country_barbados',				'BB',		1,	's2_prod'},
      {'create_acc_country_belarus',				'BY',		4,	'ru_prod'},
      {'create_acc_country_belgium',				'BE',		1,	's2_prod'},
      {'create_acc_country_belize',					'BZ',		1,	's2_prod'},
      {'create_acc_country_benin',					'BJ',		1,	's2_prod'},
      {'create_acc_country_bermuda',				'BM',		1,	's2_prod'},
      {'create_acc_country_bhutan',					'BT',		1,	's2_prod'},
      {'create_acc_country_bolivia',				'BO',		1,	's2_prod'},
      {'create_acc_country_bosnia',					'BA',		1,	's2_prod'},
      {'create_acc_country_bouvet_island',			'BV',		1,	's2_prod'},
      {'create_acc_country_brazil',					'BR',		1,	's2_prod'},
      {'create_acc_country_brit_ocean',				'IO',		1,	's2_prod'},
      {'create_acc_country_brunei',					'BN',		3,	'sea_prod'},
      {'create_acc_country_burkina',				'BF',		1,	's2_prod'},
      {'create_acc_country_burundi',				'BI',		1,	's2_prod'},
      {'create_acc_country_cambodia',				'KH',		3,	'sea_prod'},
      {'create_acc_country_cameroon',				'CM',		1,	's2_prod'},
      {'create_acc_country_canada',					'CA',		1,	's2_prod'},
      {'create_acc_country_cape_verde',				'CV',		1,	's2_prod'},
      {'create_acc_country_cayman',					'KY',		1,	's2_prod'},
      {'create_acc_country_african_rep',			'CF',		1,	's2_prod'},
      {'create_acc_country_chad',					'TD',		1,	's2_prod'},
      {'create_acc_country_czech',					'CZ',		1,	's2_prod'},
      {'create_acc_country_chile',					'CL',		1,	's2_prod'},
      {'create_acc_country_china',					'CN',		2,	'cn_prod'},
      {'create_acc_country_christmas',				'CX',		1,	's2_prod'},
      {'create_acc_country_cocos',					'CC',		1,	's2_prod'},
      {'create_acc_country_colombia',				'CO',		1,	's2_prod'},
      {'create_acc_country_comoros',				'KM',		1,	's2_prod'},
      {'create_acc_country_congo',					'CG',		1,	's2_prod'},
      {'create_acc_country_congo_dem_rep',			'CD',		1,	's2_prod'},
      {'create_acc_country_cook',					'CK',		1,	's2_prod'},
      {'create_acc_country_cote',					'CI',		1,	's2_prod'},
      {'create_acc_country_croatia',				'HR',		1,	's2_prod'},
      {'create_acc_country_cyprus',					'CY',		1,	's2_prod'},
      {'create_acc_country_denmark',				'DK',		1,	's2_prod'},
      {'create_acc_country_djibouti',				'DJ',		1,	's2_prod'},
      {'create_acc_country_dominica',				'DM',		1,	's2_prod'},
      {'create_acc_country_dominican_rep',			'DO',		1,	's2_prod'},
      {'create_acc_country_east_timor',				'TL',		3,	'sea_prod'},
      {'create_acc_country_ecuador',				'EC',		1,	's2_prod'},
      {'create_acc_country_egypt',					'EG',		1,	's2_prod'},
      {'create_acc_country_elsalvador',				'SV',		1,	's2_prod'},
      {'create_acc_country_equatorial_g',			'GQ',		1,	's2_prod'},
      {'create_acc_country_eritrea',				'ER',		1,	's2_prod'},
      {'create_acc_country_estonia',				'EE',		4,	'ru_prod'},
      {'create_acc_country_ethiopia',				'ET',		1,	's2_prod'},
      {'create_acc_country_falkland_island',		'FK',		1,	's2_prod'},
      {'create_acc_country_faroe',					'FO',		1,	's2_prod'},
      {'create_acc_country_fiji',					'FJ',		1,	's2_prod'},
      {'create_acc_country_finland',				'FI',		1,	's2_prod'},
      {'create_acc_country_france',					'FR',		1,	's2_prod'},
      {'create_acc_country_france_metro',			'FX',		1,	's2_prod'},
      {'create_acc_country_france_guiana',			'GF',		1,	's2_prod'},
      {'create_acc_country_france_poly',			'PF',		1,	's2_prod'},
      {'create_acc_country_france_south',			'TF',		1,	's2_prod'},
      {'create_acc_country_gabon',					'GA',		1,	's2_prod'},
      {'create_acc_country_gambia',					'GM',		1,	's2_prod'},
      {'create_acc_country_georgia',				'GE',		4,	'ru_prod'},
      {'create_acc_country_germany',				'DE',		1,	's2_prod'},
      {'create_acc_country_ghana',					'GH',		1,	's2_prod'},
      {'create_acc_country_gibraltar',				'GI',		1,	's2_prod'},
      {'create_acc_country_greece',					'GR',		1,	's2_prod'},
      {'create_acc_country_greenland',				'GL',		1,	's2_prod'},
      {'create_acc_country_grenada',				'GD',		1,	's2_prod'},
      {'create_acc_country_guadeloupe',				'GP',		1,	's2_prod'},
      {'create_acc_country_guam',					'GU',		1,	's2_prod'},
      {'create_acc_country_guatemala',				'GT',		1,	's2_prod'},
      {'create_acc_country_guinea',					'GN',		1,	's2_prod'},
      {'create_acc_country_guinea_bissau',			'GW',		1,	's2_prod'},
      {'create_acc_country_guyana',					'GY',		1,	's2_prod'},
      {'create_acc_country_haiti',					'HT',		1,	's2_prod'},
      {'create_acc_country_heard_mcdonald',			'HM',		1,	's2_prod'},
      {'create_acc_country_honduras',				'HN',		1,	's2_prod'},
      {'create_acc_country_hungary',				'HU',		1,	's2_prod'},
      {'create_acc_country_iceland',				'IS',		1,	's2_prod'},
      {'create_acc_country_india',					'IN',		1,	's2_prod'},
      {'create_acc_country_indonesia',				'ID',		3,	'sea_prod'},
      {'create_acc_country_ireland',				'IE',		1,	's2_prod'},
      {'create_acc_country_israel',					'IL',		1,	's2_prod'},
      {'create_acc_country_italy',					'IT',		1,	's2_prod'},
      {'create_acc_country_jamaica',				'JM',		1,	's2_prod'},
      {'create_acc_country_japan',					'JP',		1,	's2_prod'},
      {'create_acc_country_kazakhstan',				'KG',		4,	'ru_prod'},
      {'create_acc_country_kyrgyzstan',				'KZ',		4,	'ru_prod'},
      {'create_acc_country_kenya',					'KE',		1,	's2_prod'},
      {'create_acc_country_laos',					'LA',		3,	'sea_prod'},
      {'create_acc_country_latvia',					'LV',		4,	'ru_prod'},
      {'create_acc_country_lesotho',				'LS',		1,	's2_prod'},
      {'create_acc_country_liechtenstein',			'LI',		1,	's2_prod'},
      {'create_acc_country_lithuania',				'LT',		4,	'ru_prod'},
      {'create_acc_country_luxembourg',				'LU',		1,	's2_prod'},
      {'create_acc_country_macau',					'MO',		1,	's2_prod'},
      {'create_acc_country_madagascar',				'MG',		1,	's2_prod'},
      {'create_acc_country_malawia',				'MW',		1,	's2_prod'},
      {'create_acc_country_malaysia',				'MY',		3,	'sea_prod'},
      {'create_acc_country_maldives',				'MV',		1,	's2_prod'},
      {'create_acc_country_mali',					'ML',		1,	's2_prod'},
      {'create_acc_country_malta',					'MT',		1,	's2_prod'},
      {'create_acc_country_marshall',				'MH',		1,	's2_prod'},
      {'create_acc_country_martinique',				'MQ',		1,	's2_prod'},
      {'create_acc_country_mauritania',				'MR',		1,	's2_prod'},
      {'create_acc_country_mauritius',				'MU',		1,	's2_prod'},
      {'create_acc_country_mayotte',				'YT',		1,	's2_prod'},
      {'create_acc_country_mexico',					'MX',		1,	's2_prod'},
      {'create_acc_country_micronesia',				'FM',		1,	's2_prod'},
      {'create_acc_country_moldova',				'MD',		4,	'ru_prod'},
      {'create_acc_country_monaco',					'MC',		1,	's2_prod'},
      {'create_acc_country_mongolia',				'MN',		1,	's2_prod'},
      {'create_acc_country_montenegro',				'ME',		1,	's2_prod'},
      {'create_acc_country_moracco',				'MA',		1,	's2_prod'},
      {'create_acc_country_mozambique',				'MZ',		1,	's2_prod'},
      {'create_acc_country_myanmar',				'MM',		3,	'sea_prod'},
      {'create_acc_country_namibia',				'NA',		1,	's2_prod'},
      {'create_acc_country_nauru',					'NR',		1,	's2_prod'},
      {'create_acc_country_nepal',					'NP',		1,	's2_prod'},
      {'create_acc_country_netherlands',			'NL',		1,	's2_prod'},
      {'create_acc_country_netherlands_ant',		'AN',		1,	's2_prod'},
      {'create_acc_country_netherlands_sm',			'BQ',		1,	's2_prod'},
      {'create_acc_country_new_caledonia',			'NC',		1,	's2_prod'},
      {'create_acc_country_new_zealand',			'NZ',		1,	's2_prod'},
      {'create_acc_country_nicaragua',				'NI',		1,	's2_prod'},
      {'create_acc_country_niger',					'NE',		1,	's2_prod'},
      {'create_acc_country_niue',					'NU',		1,	's2_prod'},
      {'create_acc_country_norfolk_island',			'NF',		1,	's2_prod'},
      {'create_acc_country_norther_mariana',		'MP',		1,	's2_prod'},
      {'create_acc_country_norway',					'NO',		1,	's2_prod'},
      {'create_acc_country_oman',					'OM',		1,	's2_prod'},
      {'create_acc_country_pakistan',				'PK',		1,	's2_prod'},
      {'create_acc_country_palau',					'PW',		1,	's2_prod'},
      {'create_acc_country_panama',					'PA',		1,	's2_prod'},
      {'create_acc_country_papau_nguinea',			'PG',		1,	's2_prod'},
      {'create_acc_country_paraguay',				'PY',		1,	's2_prod'},
      {'create_acc_country_peru',					'PE',		1,	's2_prod'},
      {'create_acc_country_philippines',			'PH',		3,	'sea_prod'},
      {'create_acc_country_pitcairn',				'PN',		1,	's2_prod'},
      {'create_acc_country_poland',					'PL',		1,	's2_prod'},
      {'create_acc_country_portugal',				'PT',		1,	's2_prod'},
      {'create_acc_country_puerto_rico',			'PR',		1,	's2_prod'},
      {'create_acc_country_qatar',					'QA',		1,	's2_prod'},
      {'create_acc_country_romania',				'RO',		1,	's2_prod'},
      {'create_acc_country_russia',					'RU',		4,	'ru_prod'},
      {'create_acc_country_saint_kitts',			'KN',		1,	's2_prod'},
      {'create_acc_country_saint_lucia',			'LC',		1,	's2_prod'},
      {'create_acc_country_saint_vincent',			'VC',		1,	's2_prod'},
      {'create_acc_country_samoa',					'WS',		1,	's2_prod'},
      {'create_acc_country_san_marino',				'SM',		1,	's2_prod'},
      {'create_acc_country_sao_tome',				'ST',		1,	's2_prod'},
      {'create_acc_country_saudi_arabia',			'SA',		1,	's2_prod'},
      {'create_acc_country_senegal',				'SN',		1,	's2_prod'},
      {'create_acc_country_serbia',					'RS',		1,	's2_prod'},
      {'create_acc_country_seychelles',				'SC',		1,	's2_prod'},
      {'create_acc_country_sierra_leone',			'SL',		1,	's2_prod'},
      {'create_acc_country_singapore',				'SG',		3,	'sea_prod'},
      {'create_acc_country_slovakia',				'SK',		1,	's2_prod'},
      {'create_acc_country_slovenia',				'SI',		1,	's2_prod'},
      {'create_acc_country_solomon',				'SB',		1,	's2_prod'},
      {'create_acc_country_south_africa',			'ZA',		1,	's2_prod'},
      {'create_acc_country_south_korea',			'KR',		1,	's2_prod'},
      {'create_acc_country_south_ossetia',			nil,		4,	'ru_prod'},
      {'create_acc_country_spain',					'ES',		1,	's2_prod'},
      {'create_acc_country_sri_lanka',				'LK',		1,	's2_prod'},
      {'create_acc_country_sthelena',				'SH',		1,	's2_prod'},
      {'create_acc_country_stpierre',				'PM',		1,	's2_prod'},
      {'create_acc_country_sudan',					'SD',		1,	's2_prod'},
      {'create_acc_country_suriname',				'SR',		1,	's2_prod'},
      {'create_acc_country_svalbard',				'SJ',		1,	's2_prod'},
      {'create_acc_country_swaziland',				'SZ',		1,	's2_prod'},
      {'create_acc_country_sweden',					'SE',		1,	's2_prod'},
      {'create_acc_country_switzerland',			'CH',		1,	's2_prod'},
      {'create_acc_country_syria',					'SY',		1,	's2_prod'},
      {'create_acc_country_tajikistan',				'TJ',		4,	'ru_prod'},
      {'create_acc_country_turkmenistan',			'TM',		4,	'ru_prod'},
      {'create_acc_country_tanzania',				'TZ',		1,	's2_prod'},
      {'create_acc_country_thailand',				'TH',		3,	'sea_prod'},
      {'create_acc_country_togo',					'TG',		1,	's2_prod'},
      {'create_acc_country_tonga',					'TO',		1,	's2_prod'},
      {'create_acc_country_trinidad',				'TT',		1,	's2_prod'},
      {'create_acc_country_tunisia',				'TN',		1,	's2_prod'},
      {'create_acc_country_turkey',					'TR',		1,	's2_prod'},
      {'create_acc_country_turks_and_caicos',		'TC',		1,	's2_prod'},
      {'create_acc_country_uganda',					'UG',		1,	's2_prod'},
      {'create_acc_country_ukraine',				'UA',		4,	'ru_prod'},
      {'create_acc_country_united_kingdom',			'GB',		1,	's2_prod'},
	  {'create_acc_country_united_states',			'US',		1,	's2_prod'},	  
      {'create_acc_country_us_minor',				'UM',		1,	's2_prod'},
      {'create_acc_country_uruguay',				'UY',		1,	's2_prod'},
      {'create_acc_country_uzbekistan',				'UZ',		4,	'ru_prod'},
      {'create_acc_country_vanuatu',				'VU',		1,	's2_prod'},
      {'create_acc_country_vatican',				'VA',		1,	's2_prod'},
      {'create_acc_country_venezuela',				'VE',		1,	's2_prod'},
      {'create_acc_country_vietnam',				'VN',		3,	'sea_prod'},
      {'create_acc_country_virgin_brit',			'VG',		1,	's2_prod'},
      {'create_acc_country_virgin_us',				'VI',		1,	's2_prod'},
      {'create_acc_country_wallis',					'WF',		1,	's2_prod'},
      {'create_acc_country_western_sahara',			'EH',		1,	's2_prod'},
      {'create_acc_country_zaire',					'CD',		1,	's2_prod'},
}

if (GetCvarString('build_branch') == 'dev') or (GetCvarString('build_branch') == 'pt') then
	-- build_branch left out of prod branches as they should be region dependant
	table.insert(Login.regionsTable, {'dev',				'dev',		1,	's2_development'})
	table.insert(Login.regionsTable, {'pt',					'pt',		1,	's2_private_test'})
	table.insert(Login.regionsTable, {'staging',			'staging',	1,	's2_staging'})
	table.insert(Login.regionsTable, {'rc',					nil,		1,	's2_rc'})
	table.insert(Login.regionsTable, {'s2_prod_crippled',	nil,		1,	's2_prod_crippled'})
	table.insert(Login.regionsTable, {'s2_prod',			nil,		1,	's2_prod'})
	table.insert(Login.regionsTable, {'demo_tutorial1',		nil,		1,	'demo_tutorial1'})
	table.insert(Login.regionsTable, {'demo_tutorial3',		nil,		1,	'demo_tutorial3'})
	table.insert(Login.regionsTable, {'sea_rc',				'sea_rc',	1,	'sea_rc'})
	table.insert(Login.regionsTable, {'sea_prod',			nil,		1,	'sea_prod'})
	table.insert(Login.regionsTable, {'ru_rc',				'ru_rc',	1,	'ru_rc'})
	table.insert(Login.regionsTable, {'ru_prod',			nil,		1,	'ru_prod'})
	table.insert(Login.regionsTable, {'cn_rc',				'cn_rc',	1,	'cn_rc'})
	table.insert(Login.regionsTable, {'cn_prod',			nil,		1,	'cn_prod'})
end

function FindCountryStringKeyFromISOCode(isoCode)
	for i, v in ipairs(Login.regionsTable) do
		if (v) and (isoCode) and (v[2]) and (v[2] == isoCode) then
			return v[1]
		end
	end
	return nil
end
