
-- End Match
local container					= object:GetWidget('endMatchContainer')

endMatchRandomGroupNames = {
	'Fieldings Over 40',
	'Fieldings Under 40',
	'Fourty Fieldings'
}

endMatchRewardDataTemp = {
	nickname	= merc,
	ident_id	= 9.005,
	uniqid		= 6071,
	reward	= {
		currentEssence	= 0,
		reward3Essence	= 0,
		currentGems		= 0,
		progress		= 1,
		reward2Ore		= 0,
		reward1Ore		= 0,
		gemsEarned		= 0,
		displayBox1		= 2,
		displayBox2		= 4,
		shard			= 005,
		reward3Ore		= 0,
		reward2Food		= 0,
		reward4Food		= 0,
		oreEarned		= 0,
		reward2Tier		= 0,
		wasOpened		= 0,
		reward1Essence	= 0,
		forceSaved		= 0,
		reward2Shards	= 0,
		identIncrement	= 9,
		reward1Tier		= 0,
		reward2Essence	= 0,
		fromCache		= 0,
		currentTier		= 0,
		reward2UberFood	= 0,
		reward1UberFood	= 0,
		currentUberFood	= 0,
		currentShards	= 0,
		match_id		= 42.004,
		displayBox3		= 6,
		currentOre		= 0,
		reward4UberFood	= 0,
		numberOfPrizes	= 4,
		reward3UberFood	= 0,
		reward4Shards	= 0,
		shardsEarned	= 0,
		reward4Ore		= 0,
		reward4Gems		= 0,
		reward4Essence	= 0,
		reward4Tier		= 0,
		reward3Shards	= 0,
		reward3Gems		= 0,
		reward1Gems		= 0,
		reward3Food		= 0,
		foodEarned		= 0,
		reward3Tier		= 0,
		displayBox4		= 1,
		used			= 0,
		reward1Food		= 0,
		currentFood		= 0,
		reward2Gems		= 0,
		reward1Shards	= 0,
		newInstance		= 1,
		essenceEarned	= 0,
		uberFoodEarned	= 0,
	}
}

endMatchStatsDataTemp = {
	map				= 1,
	version			= 0,
	mapVersion		= 0,
	server_id		= 2.009,
	match_id		= 42.004,
	slave			= 1,
	matchStats		= {
		forceSaved		= 0,
		matchIncrement	= 42,
		shard			= 004,
		newInstance		= 1,
		fromCache		= 1,
		stats			= {
			[1]				= {
				hero		= 'Hero_Rook',
				pet			= 'Familiar_Pincer',
				nickname	= 'Bot1',
				hero_id		= 3,
				creepKills	= 0,
				slot		= 6,
				deaths		= 0,
				item_1		= 76,
				item_2		= 24,
				item_3		= '',
				item_4		= '',
				item_5		= '',
				item_6		= '',
				match_id	= 42.004,
				ident_id	= 4294967.295,
				kills		= 0,
				winner		= 1,
				gpm			= 0,
			},
			[0]				= {
				hero		= 'Hero_Minerva',
				nickname	= 'Bot2',
				pet			= 'Familiar_Mystik',
				hero_id		= 33,
				creepKills	= 0,
				slot		= 5,
				deaths		= 0,
				item_1		= 43,
				item_2		= 24,
				item_3		= '',
				item_4		= '',
				item_5		= '',
				item_6		= '',
				match_id	= 42.004,
				ident_id	= 4294967.295,
				kills		= 0,
				winner		= 1,
				gpm			= 0,
			},
			[3]				= {
				hero		= 'Hero_Bastion',
				nickname	= 'Bot3',
				pet			= 'Familiar_Luster',
				hero_id		= 4,
				creepKills	= 0,
				slot		= 8,
				deaths		= 0,
				item_1		= 66,
				item_2		= 24,
				item_3		= '',
				item_4		= '',
				item_5		= '',
				item_6		= '',
				match_id	= 42.004,
				ident_id	= 4294967.295,
				kills		= 0,
				winner		= 1,
				gpm			= 0,
				damage		= 8234,
			},
			[2]				= {
				hero		= 'Hero_Carter',
				nickname	= 'Bot4',
				pet			= 'Familiar_Razer',
				hero_id		= 5,
				creepKills	= 0,
				slot		= 7,
				deaths		= 0,
				item_1		= 9,
				item_2		= 4,
				item_3		= 24,
				item_4		= '',
				item_5		= '',
				item_6		= '',
				match_id	= 42.004,
				ident_id	= 4294967.295,
				kills		= 0,
				winner		= 1,
				gpm			= 0,
				damage		= 5322,
			},
			[5]				= {
				hero		= 'Hero_Ladytinder',
				nickname	= 'Merc',
				pet			= 'Familiar_Bounder',
				hero_id		= 5,
				creepKills	= 0,
				slot		= 0,
				deaths		= 3,
				item_1		= 'Item_Codex',
				item_2		= 'Item_Frostbrand',
				item_3		= 'Item_FellBlade',
				item_4		= 'Item_Soulstealer',
				item_5		= 'Item_ThunderClaw',
				item_6		= 'Item_Timewarper',
				match_id	= 42.004,
				ident_id	= '9.005',
				kills		= 25,
				winner		= 0,
				gpm			= 521,
				damage		= 9423,
			},
			[4]				= {
				hero		= 'Hero_Ace',
				nickname	= 'Bot5',
				pet			= 'Familiar_Topps',
				hero_id		= 5,
				creepKills	= 0,
				slot		= 9,
				deaths		= 0,
				item_1		= 9,
				item_2		= 4,
				item_3		= 24,
				item_4		= '',
				item_5		= '',
				item_6		= '',
				match_id	= 42.004,
				ident_id	= 4294967.295,
				kills		= 0,
				winner		= 0,
				gpm			= 0,
				damage		= 5445,
			},
			[7]				= {
				hero		= 'Hero_Vermillion',
				nickname	= 'Bot6',
				pet			= 'Familiar_Mystik',
				hero_id		= 11,
				creepKills	= 0,
				slot		= 2,
				deaths		= 0,
				item_1		= 9,
				item_2		= 4,
				item_3		= 24,
				item_4		= '',
				item_5		= '',
				item_6		= '',
				match_id	= 42.004,
				ident_id	= 4294967.295,
				kills		= 0,
				winner		= 0,
				gpm			= 0,
				damage		= 3232,
			},
			[6]				= {
				hero		= 'Hero_Ace',
				nickname	= 'Bot7',
				pet			= 'Familiar_Pincer',
				hero_id		= 18,
				creepKills	= 0,
				slot		= 1,
				deaths		= 0,
				item_1		= 9,
				item_2		= 4,
				item_3		= 24,
				item_4		= '',
				item_5		= '',
				item_6		= '',
				match_id	= 42.004,
				ident_id	= 4294967.295,
				kills		= 0,
				winner		= 0,
				gpm			= 0,
				damage		= 1232,
			},
			[9]				= {
				hero		= 'Hero_Minerva',
				nickname	= 'Bot8',
				pet			= 'Familiar_Luster',
				hero_id		= 33,
				creepKills	= 0,
				slot		= 4,
				deaths		= 0,
				item_1		= 9,
				item_2		= 4,
				item_3		= 24,
				item_4		= '',
				item_5		= '',
				item_6		= '',
				match_id	= 42.004,
				ident_id	= 4294967.295,
				kills		= 0,
				winner		= 0,
				gpm			= 0,
				damage		= 4500,
			},
			[8]				= {
				hero		= 'Hero_Rook',
				nickname	= 'Bot9',
				pet			= 'Familiar_Tortus',
				hero_id		= 3,
				creepKills	= 0,
				slot		= 3,
				deaths		= 0,
				item_1		= 9,
				item_2		= 4,
				item_3		= 24,
				item_4		= '',
				item_5		= '',
				item_6		= '',
				match_id	= 42.004,
				ident_id	= 4294967.295,
				kills		= 0,
				winner		= 0,
				gpm			= 0,
				damage		= 34324,
			}
		}
	}
}

endMatchRewardsTempLuckReasons = {
	'Good Karma',
	'Being Social',
	'Some Call2Action'
}

-- container:RegisterWatchLua('LoginStatus', function(widget, trigger)	-- Pretty much a hack
	-- if trigger.isLoggedIn and trigger.hasIdent then
		-- endMatchStatsDataTemp.matchStats.stats[5].ident_id = tostring(GetIdentID())
	-- end
	
-- end, false, nil, 'hasIdent', 'isLoggedIn')


-- container:RegisterWatchLua('AccountInfo', function(widget, trigger)
	-- endMatchStatsDataTemp.matchStats.stats[5].nickname = trigger.nickname
-- end, false, nil, 'nickname')

function testEndMatchPopulate()
	local container					= GetWidget('endMatchContainer')
	local triggerStatus				= LuaTrigger.GetTrigger('PostGameLoopStatus')
	container:SetVisible(true)
	endMatchProcessRewardData(endMatchRewardDataTemp)
	endMatchProcessStatsData(endMatchStatsDataTemp)

	triggerStatus:Trigger(false)
end